apiVersion: v1
kind: Service
metadata:
  name: ud-reverseproxy
  labels:
    app: ud-reverseproxy
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: ud-reverseproxy
  type: LoadBalancer
